Add coverage workflow
ispras/casr pull request #161
Opened 2023-10-04 09:37 UTC by hkctkuy

2023-10-04 11:12 UTC, SweetVishnya commented
Can you also add a badge?

2023-10-04 11:15 UTC, SweetVishnya requested changes

2023-10-04 11:15 UTC, SweetVishnya commented on .github/workflows/coverage.yaml
> +    branches: [ master, coverage ]
Remove coverage branch

2023-10-05 13:55 UTC, hkctkuy commented on .github/workflows/coverage.yaml
> +    branches: [ master, coverage ]
Done

2023-10-06 15:38 UTC, SweetVishnya requested changes
Don't we want to run tests and collect coverage for them at the same time?

2023-10-06 15:38 UTC, SweetVishnya commented on README.md
> +[![codecov](https://codecov.io/github/ispras/casr/graph/badge.svg?token=D9VY1WRWA7)](https://codecov.io/github/ispras/casr)
You may add it next to docs badge

2023-10-06 15:58 UTC, hkctkuy commented on README.md
> +[![codecov](https://codecov.io/github/ispras/casr/graph/badge.svg?token=D9VY1WRWA7)](https://codecov.io/github/ispras/casr)
Done

2023-10-06 16:01 UTC, SweetVishnya approved these changes

2023-10-06 16:49 UTC, anfedotoff approved these changes

2023-10-09 10:23 UTC, merged