Adding MacOS Support
ispras/casr pull request #203
Opened 2024-02-29 20:00 UTC by njelich

Hi! I played around with getting this to work on Mac, two main elements to get around were the linux_personality usage and lsb_release for getting some info. Both of those should be working fine, but I am getting some different behavior from tests.

I couldn't dig much deeper into these, but in general I get something like this in these tests, related to GDB

```
Stdout GDB output: ["", "$4 = void", "", "", "", ""]
Error: SiginfoParse("Siginfo string: $4 = void doesn't match regex template")
.
 Stderr: Error: Program terminated (no crash)
```

I would appreciate some direction. Thanks :) Hopefully we can port this amazing tool of Mac, and if LLDB is implemented instead of GDB even on M1 Macs (since GDB doesn't support M1 yet).

2024-02-29 20:03 UTC, njelich commented
Requesting reviewer from @anfedotoff

2024-02-29 21:20 UTC, SweetVishnya commented
AFAIK, `uname` won't print Ubuntu distro version.

2024-02-29 21:21 UTC, anfedotoff requested changes

2024-02-29 21:29 UTC, Avgor46 commented
> I would appreciate some direction

We use precompiled binaries in tests, so they are in elf format. I think you should try to recompile them.

2024-02-29 22:01 UTC, anfedotoff commented
Hi, @njelich!
Thanks, it's a great idea to support Mac!
As for GDB tests, the error occurs [here](https://github.com/anfedotoff/gdb-command/blob/master/src/siginfo.rs#L34). 
`$4 = void` looks like that no signal was cached by gdb. We use this [command](https://github.com/anfedotoff/gdb-command/blob/master/src/lib.rs#L316) for that.
I think, we should recompile gdb tests for Mac, to get them work. You can look at this [Makefile](casr/tests/casr_tests/x86_Makefile).
Maybe the right way is to compile binaries in tests, the way we do [here](https://github.com/ispras/casr/blob/master/casr/tests/tests.rs#L1730) for example.

2024-02-29 23:02 UTC, Avgor46 commented
I found that vanilla gdb from brew could not run properly on MacOS due to [this](https://sourceware.org/gdb/wiki/PermissionsDarwin)

2024-03-01 08:54 UTC, anfedotoff commented on .github/workflows/darwin-i386.yml
> +name: darwin-i386
Let's rename darwin-i386 to darwin-x86-64. I suppose, macos-latest runs on x86-64, according to  https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md. Also we should rename .yaml file and job name too.

2024-03-10 12:47 UTC, SweetVishnya requested changes

2024-03-10 12:48 UTC, SweetVishnya commented
The code itself looks good to me. The next thing left is to recompile tests with Makefile.

2024-03-10 12:50 UTC, SweetVishnya commented
Btw, the `Brew packages` CI step fails

2024-03-10 20:21 UTC, njelich commented on libcasr/src/report.rs
> +            let mut os_cmd = Command::new("sw_vers");
Well, `sw_vers` is a built in utility of the MacOS, so there is no need to install it.

2024-03-10 21:11 UTC, njelich commented
@SweetVishnya I made progress with the CI and GDB install on M1 Mac. Re recompiling the tests, do I simply run the [x86 Makefile](https://github.com/ispras/casr/blob/master/casr/tests/casr_tests/x86_Makefile) at the start of the test CI?

2024-03-11 06:56 UTC, Avgor46 commented
We have the following tests:
 
1) coredump tests
2) clustering tests
3) casr-san tests
4) casr-gdb tests
5) other languages tests
6) fuzzers



The first kind should not be tested on Mac OS. Second works well. For 3-4 you just need to recompile using Makefile. Tests for 5-6 categories we should discuss.

2024-03-11 07:05 UTC, SweetVishnya commented
However, there is still some ELF and signal dependent code:

https://github.com/ispras/casr/blob/master/libcasr/src/gdb/exploitable.rs

2024-03-11 21:02 UTC, njelich commented
I disabled the coredump tests, it passes now

2024-03-12 06:21 UTC, SweetVishnya commented on README.md
> +[![darwin](https://github.com/ispras/casr/actions/workflows/darwin.yml/badge.svg?branch=master)](https://github.com/ispras/casr/actions/workflows/darwin.yml)
Maybe, we should explicitly state that it is darwin-x86?

2024-03-12 09:33 UTC, njelich commented
@SweetVishnya What should it be named then?

https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Because there will be no more Intel macs

2024-03-12 11:42 UTC, SweetVishnya commented
@Avgor46 could you help with proper naming, please?

2024-03-12 12:52 UTC, Avgor46 commented
Maybe `darwin-arm64`?

2024-03-13 19:12 UTC, njelich commented
Updated to `darwin-arm64`, please verify and merge.

2024-03-14 06:33 UTC, SweetVishnya approved these changes

2024-03-14 06:39 UTC, SweetVishnya commented
@njelich, althoug, almost all of the tests are disabled. Have you tried to manually run casr-libfuzzer and casr-gdb? Do you have any screenshots?

2024-03-17 11:04 UTC, merged