Workspace: casr & libcasr
ispras/casr pull request #49
Opened 2023-03-14 18:34 UTC by anfedotoff

Closes #39

2023-03-15 09:34 UTC, SweetVishnya requested changes

2023-03-15 09:34 UTC, SweetVishnya commented on Cargo.toml
> +debug = true
disable debug in release

2023-03-15 09:34 UTC, SweetVishnya commented on casr/Cargo.toml
> +libcasr = { path = "../libcasr", version = "2.4.0", features = ["serde", "exploitable"] }
do we need to specify version here?

2023-03-15 09:34 UTC, SweetVishnya commented on casr/Cargo.toml
> +libcasr = { path = "../libcasr", version = "2.4.0", features = ["serde", "exploitable"] }
It will complicate making releases

2023-03-15 09:34 UTC, SweetVishnya commented on casr/src/bin/casr-san.rs
> +                    4 | 31 => {
Why did we remove the constants?

2023-03-15 09:34 UTC, SweetVishnya commented on libcasr/Cargo.toml
> +version = "2.4.0"
Did you modify update version script?

2023-03-15 09:34 UTC, SweetVishnya commented on libcasr/Cargo.toml
> +lazy_static = "~1.4"
dev-dependecies?

2023-03-15 09:36 UTC, anfedotoff commented on casr/src/bin/casr-san.rs
> +                    4 | 31 => {
They are defined in gdb.rs

2023-03-15 09:36 UTC, anfedotoff commented on libcasr/Cargo.toml
> +version = "2.4.0"
yes

2023-03-15 09:36 UTC, anfedotoff commented on libcasr/Cargo.toml
> +lazy_static = "~1.4"
for tests

2023-03-15 10:08 UTC, SweetVishnya commented on casr/src/bin/casr-san.rs
> +                    4 | 31 => {
Can we move them to libcasr

2023-03-15 10:23 UTC, anfedotoff commented on casr/src/bin/casr-san.rs
> +                    4 | 31 => {
I will move to file with constants.rs

2023-03-15 11:22 UTC, SweetVishnya requested changes

2023-03-15 11:22 UTC, SweetVishnya commented on update_version.sh
> +sed -i "s/\"$1\"/\"$2\"/g" casr/src/bin/casr-core.rs
Maybe we can use find casr-* to automatically add new tools?

2023-03-15 11:33 UTC, SweetVishnya commented
Add casr and libcasr crate docs. Docs for util module in casr. Update constants module docs.

2023-03-16 10:11 UTC, SweetVishnya commented on update_version.sh
> +sed -i "s/\"$1\"/\"$2\"/g" casr/src/bin/casr-core.rs
ok

2023-03-16 11:52 UTC, SweetVishnya approved these changes

2023-03-16 11:52 UTC, merged