gdb severity estimation for riscv
ispras/casr pull request #78
Opened 2023-05-12 10:22 UTC by anfedotoff

2023-05-12 10:22 UTC, anfedotoff commented
Closes #60

2023-05-12 11:01 UTC, SweetVishnya requested changes

2023-05-14 08:55 UTC, anfedotoff commented on libcasr/src/gdb/exploitable.rs
> +        ExecutionClass::find("AccessViolation")
This is a base class for all SIGSEGV crashes, according to !exploitable.

2023-05-14 08:57 UTC, anfedotoff commented on libcasr/src/gdb/exploitable.rs
> +                    _ => return ExecutionClass::find("AccessViolation"),
I looked, x86 have some different logic, better not to touch. riscv/aarch64/arm32 could have a function.

2023-05-15 11:08 UTC, merged