Casr report: "Stdin" field
ispras/casr pull request #9
Opened 2022-11-02 14:37 UTC by Avgor46

2022-11-02 17:50 UTC, SweetVishnya requested changes

2022-11-02 17:50 UTC, SweetVishnya commented on src/bin/casr-san.rs
> +    if let Some(mut file_path) = stdin_file.clone() {
We should do the similar in casr-gdb.

2022-11-03 11:43 UTC, Avgor46 commented on src/bin/casr-san.rs
> +    if let Some(mut file_path) = stdin_file.clone() {
Done

2022-11-03 11:56 UTC, SweetVishnya commented
We should add some tests for new stdin field.

2022-11-03 13:03 UTC, Avgor46 commented
> We should add some tests for new stdin field.

Added 2 tests for stdin field (with casr-san report and casr-gdb report)

2022-11-03 13:41 UTC, merged